### ISSUE TITLE
renderDiagrammeR / DiagrammeROutput broken

### ISSUE THREAD

**Issue by statwonk** [rich-iannone/DiagrammeR#149]
I plan to dig in to see if I can solve it, but `renderDiagrammeR` and `DiagrammeROutput` currently appear broken to me (`DiagrammeR_0.8.1`).

I put a reprex together here: `runGist("https://gist.github.com/statwonk/623cebaab9da7d3938d9")`

That yields the errror: `'undefined' is not an object (evaluating 'x[0]')`

**Comment by statwonk** [comment]
It looks like the error is thrown in `DiagrammeR.js` @ [L124](https://github.com/rich-iannone/DiagrammeR/blob/02c61929241bfe73397292e56cd2b78608f82465/inst/htmlwidgets/DiagrammeR.js#L124).

**Comment by statwonk** [comment]
Ahh, I see this isn't an actual bug, I was just confused by the functionality of `renderDiagrammeR` and `DiagrammeROutput`, for example below works,

```r
library(shiny)
library(DiagrammeR)
library(magrittr)

ui = shinyUI(fluidPage(
  DiagrammeROutput('diagram')
))

server = shinyServer(function(input, output) {
  output$diagram <- renderDiagrammeR(
    mermaid("graph LR; A-->B; A-->C; C-->E; B-->D; C-->D; D-->F; E-->F")
  )
})

shinyApp(ui, server)
```

**Comment by happyshows** [comment]
@statwonk your example no longer works on CRAN 0.8.1

**Comment by rich-iannone** [comment]
@happyshows @statwonk I'll get an 8.2 release of DiagrammeR out on CRAN right away. I'll test out this example to make sure it works as well.

**Comment by happyshows** [comment]
@rich-iannone One more piece of info that might help your testing. I just tried renderGrViz + grVizOutput and confirmed they work. I think the problem with renderDiagrammeR+DiagrammeROutput is it somehow failed to translate the digraph codes into vis on shiny.

**Comment by vnijs** [comment]
I assume this is related ... The example below works in Rstudio but nor from R using either the CRAN or the github version of DiagrammeR. Error: `t.getTransformToElement is not a function`

```r
DiagrammeR::mermaid("graph LR\n id1[ ] --- |Sign with Movie Company| id2(( ))\n id1[ ] --- |Sign with TV Network| id6(( ))\nid2 --- |Small Box Office: 0.3| id3[$200,000]\nid2 --- |Medium Box Office: 0.6| id4[$1,000,000]\nid2 --- |Large Box Office: 0.1| id5[$3,000,000]\nid6 --- |Small Box Office: 0.3| id7[$900,000]\nid6 --- |Medium Box Office: 0.6| id8[$900,000]\nid6 --- |Large Box Office: 0.1| id9[$900,000]\nclassDef default fill:none, bg:none, stroke-width:0px;\n    classDef chance fill:#FF8C00,stroke:#333,stroke-width:1px;\n    classDef decision fill:#9ACD32,stroke:#333,stroke-width:1px;\n    class id1 decision;\n    class id2,id6 chance;")
```

parse error with graph LR
 id1[ ] --- |Sign with Movie Company| id2(( ))
 id1[ ] --- |Sign with TV Network| id6(( ))
id2 --- |Small Box Office: 0.3| id3[$200,000]
id2 --- |Medium Box Office: 0.6| id4[$1,000,000]
id2 --- |Large Box Office: 0.1| id5[$3,000,000]
id6 --- |Small Box Office: 0.3| id7[$900,000]
id6 --- |Medium Box Office: 0.6| id8[$900,000]
id6 --- |Large Box Office: 0.1| id9[$900,000]
classDef default fill:none, bg:none, stroke-width:0px;
    classDef chance fill:#FF8C00,stroke:#333,stroke-width:1px;
    classDef decision fill:#9ACD32,stroke:#333,stroke-width:1px;
    class id1 decision;
    class id2,id6 chance;
t.getTransformToElement is not a function

**Comment by stephlocke** [comment]
I just got the same as @vnijs - works locally (Windows) but did not work via Travis 
https://github.com/stephlocke/RMSFTDP/blob/master/vignettes/RMicrosoft.Rmd
outputs to 
http://stephlocke.github.io/RMSFTDP/RMicrosoft.html

with error message:
`t.getTransformToElement is not a function`

**Comment by vnijs** [comment]
@stephlocke Have you tried the version on github? Seems to work fine on windows and mac although there are some issues with the css (see https://github.com/rich-iannone/DiagrammeR/pull/160)

**Comment by stephlocke** [comment]
Using dev version adds a .section class with an opacity of 0.2 that affects my whole doc 
http://stephlocke.github.io/RMSFTDP/RMicrosoft.html

**Comment by vnijs** [comment]
@rich-iannone Do you have a time-line to push 0.8.3 to CRAN?

**Comment by rich-iannone** [comment]
@vnijs It took a bit longer than anticipated, but I just submitted 0.8.3 to CRAN.

**Comment by vnijs** [comment]
Thanks @rich-iannone!
